
import React from 'react';
import DataTable from '@/components/DataTable';
import { Badge } from '@/components/ui/badge';
import { useDataManager } from '@/hooks/useDataManager';

const Reports = () => {
  const initialReportsData = [
    {
      id: "RPT-001",
      reportName: "Monthly Case Summary",
      category: "Case Management",
      description: "Summary of all cases for the current month",
      lastGenerated: "2024-01-12",
      generatedBy: "Sarah Wilson",
      format: "PDF",
      status: "Available",
      frequency: "Monthly",
      recipients: "Management Team",
      fileSize: "2.4 MB",
      downloadCount: 15
    },
    {
      id: "RPT-002",
      reportName: "Financial Performance Report",
      category: "Financial",
      description: "Revenue, expenses, and profitability analysis",
      lastGenerated: "2024-01-11",
      generatedBy: "John Davis",
      format: "Excel",
      status: "Available",
      frequency: "Weekly",
      recipients: "Partners",
      fileSize: "1.8 MB",
      downloadCount: 8
    },
    {
      id: "RPT-003",
      reportName: "Client Activity Report",
      category: "Client Management",
      description: "Client interactions and case progress tracking",
      lastGenerated: "2024-01-10",
      generatedBy: "Emily Brown",
      format: "PDF",
      status: "Processing",
      frequency: "Bi-weekly",
      recipients: "All Staff",
      fileSize: "3.2 MB",
      downloadCount: 22
    },
    {
      id: "RPT-004",
      reportName: "Compliance Audit Report",
      category: "Compliance",
      description: "Legal compliance and regulatory requirements review",
      lastGenerated: "2024-01-08",
      generatedBy: "Michael Johnson",
      format: "PDF",
      status: "Available",
      frequency: "Quarterly",
      recipients: "Compliance Team",
      fileSize: "5.1 MB",
      downloadCount: 5
    },
    {
      id: "RPT-005",
      reportName: "Employee Performance Report",
      category: "Human Resources",
      description: "Staff performance metrics and evaluation summary",
      lastGenerated: "2024-01-05",
      generatedBy: "Sarah Wilson",
      format: "Excel",
      status: "Expired",
      frequency: "Monthly",
      recipients: "HR Department",
      fileSize: "1.5 MB",
      downloadCount: 12
    }
  ];

  const {
    data,
    addItem,
    updateItem,
    deleteItem,
    exportData
  } = useDataManager({
    initialData: initialReportsData,
    entityName: 'Report'
  });

  const columns = [
    {
      key: 'reportName',
      label: 'Report Name',
      sortable: true,
      filterable: true
    },
    {
      key: 'category',
      label: 'Category',
      sortable: true,
      filterable: true,
      filterOptions: ['Case Management', 'Financial', 'Client Management', 'Compliance', 'Human Resources'],
      render: (value: string) => {
        const colors = {
          'Case Management': 'bg-blue-100 text-blue-800',
          'Financial': 'bg-green-100 text-green-800',
          'Client Management': 'bg-purple-100 text-purple-800',
          'Compliance': 'bg-orange-100 text-orange-800',
          'Human Resources': 'bg-pink-100 text-pink-800'
        };
        return (
          <Badge className={colors[value as keyof typeof colors]}>
            {value}
          </Badge>
        );
      }
    },
    {
      key: 'lastGenerated',
      label: 'Last Generated',
      sortable: true,
      filterable: true
    },
    {
      key: 'generatedBy',
      label: 'Generated By',
      sortable: true,
      filterable: true
    },
    {
      key: 'format',
      label: 'Format',
      sortable: true,
      filterable: true,
      filterOptions: ['PDF', 'Excel', 'CSV'],
      render: (value: string) => (
        <Badge variant="outline">{value}</Badge>
      )
    },
    {
      key: 'status',
      label: 'Status',
      sortable: true,
      filterable: true,
      filterOptions: ['Available', 'Processing', 'Expired', 'Failed'],
      render: (value: string) => {
        const colors = {
          'Available': 'bg-green-100 text-green-800',
          'Processing': 'bg-yellow-100 text-yellow-800',
          'Expired': 'bg-red-100 text-red-800',
          'Failed': 'bg-red-200 text-red-900'
        };
        return (
          <Badge className={colors[value as keyof typeof colors]}>
            {value}
          </Badge>
        );
      }
    },
    {
      key: 'frequency',
      label: 'Frequency',
      sortable: true,
      filterable: true,
      filterOptions: ['Daily', 'Weekly', 'Bi-weekly', 'Monthly', 'Quarterly']
    },
    {
      key: 'fileSize',
      label: 'File Size',
      sortable: true,
      filterable: true
    },
    {
      key: 'downloadCount',
      label: 'Downloads',
      sortable: true,
      filterable: true,
      render: (value: number) => (
        <Badge className="bg-blue-100 text-blue-800">{value}</Badge>
      )
    }
  ];

  const fields = [
    { key: 'reportName', label: 'Report Name', type: 'text' as const, required: true },
    { 
      key: 'category', 
      label: 'Category', 
      type: 'select' as const,
      options: ['Case Management', 'Financial', 'Client Management', 'Compliance', 'Human Resources'],
      required: true 
    },
    { key: 'description', label: 'Description', type: 'textarea' as const, required: true },
    { key: 'lastGenerated', label: 'Last Generated', type: 'date' as const },
    { key: 'generatedBy', label: 'Generated By', type: 'text' as const, required: true },
    { 
      key: 'format', 
      label: 'Format', 
      type: 'select' as const,
      options: ['PDF', 'Excel', 'CSV'],
      required: true 
    },
    { 
      key: 'status', 
      label: 'Status', 
      type: 'select' as const,
      options: ['Available', 'Processing', 'Expired', 'Failed'],
      required: true 
    },
    { 
      key: 'frequency', 
      label: 'Frequency', 
      type: 'select' as const,
      options: ['Daily', 'Weekly', 'Bi-weekly', 'Monthly', 'Quarterly'],
      required: true 
    },
    { key: 'recipients', label: 'Recipients', type: 'text' as const },
    { key: 'fileSize', label: 'File Size', type: 'text' as const },
    { key: 'downloadCount', label: 'Download Count', type: 'number' as const }
  ];

  return (
    <div className="p-6">
      <DataTable
        title="Reports & Analytics"
        columns={columns}
        data={data}
        fields={fields}
        searchPlaceholder="Search reports by name, category, or generated by..."
        onAdd={addItem}
        onEdit={updateItem}
        onDelete={deleteItem}
        onExport={exportData}
        entityName="Report"
      />
    </div>
  );
};

export default Reports;
