-- Insert sample hearing data for testing
INSERT INTO public.hearings (
  case_id,
  client_id, 
  lawyer_id,
  hearing_date,
  hearing_time,
  duration,
  hearing_number,
  title,
  description,
  court_name,
  court_room,
  judge_name,
  hearing_type,
  status,
  outcome,
  notes
) VALUES 
(
  gen_random_uuid(),
  gen_random_uuid(),
  gen_random_uuid(),
  '2024-02-15',
  '10:00',
  '02:00:00',
  'H001-2024',
  'Initial Case Review Hearing',
  'First hearing to review case documents and establish timeline',
  'High Court of Delhi',
  'Court Room 12',
  'Justice Rajesh Kumar',
  'Motion Hearing',
  'scheduled',
  NULL,
  'Client needs to bring original documents'
),
(
  gen_random_uuid(),
  gen_random_uuid(),
  gen_random_uuid(),
  '2024-02-20',
  '14:30',
  '01:30:00',
  'H002-2024',
  'Evidence Submission Hearing',
  'Hearing for submission of key evidence and witness statements',
  'District Court Mumbai',
  'Court Room 8',
  'Justice Priya Sharma',
  'Trial',
  'confirmed',
  NULL,
  'All evidence documents prepared and verified'
),
(
  gen_random_uuid(),
  gen_random_uuid(),
  gen_random_uuid(),
  '2024-02-10',
  '11:15',
  '01:00:00',
  'H003-2024',
  'Settlement Conference',
  'Mediation hearing to explore settlement options',
  'Family Court Bangalore',
  'Court Room 5',
  'Justice Arun Patel',
  'Settlement Conference',
  'completed',
  'Settlement reached - case resolved',
  'Successful mediation resulted in mutual agreement'
),
(
  gen_random_uuid(),
  gen_random_uuid(),
  gen_random_uuid(),
  '2024-03-01',
  '09:45',
  '03:00:00',
  'H004-2024',
  'Final Judgment Hearing',
  'Final hearing for case judgment and verdict',
  'Supreme Court of India',
  'Court Room 2',
  'Chief Justice Meera Singh',
  'Final Hearing',
  'scheduled',
  NULL,
  'Prepare final arguments and closing statements'
),
(
  gen_random_uuid(),
  gen_random_uuid(),
  gen_random_uuid(),
  '2024-01-28',
  '13:00',
  '00:45:00',
  'H005-2024',
  'Motion to Dismiss Hearing',
  'Hearing on defendant motion to dismiss the case',
  'Civil Court Chennai',
  'Court Room 15',
  'Justice Vikram Joshi',
  'Motion Hearing',
  'postponed',
  NULL,
  'Postponed due to missing documentation - rescheduled for next week'
);