// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibaqunlwzzoonbsnajbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliYXF1bmx3enpvb25ic25hamJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjUxMzAsImV4cCI6MjA2NTIwMTEzMH0.zavTfXDwRA9an7BAuW4RrMU3LHuJDIF2u57V2onEPIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});